"""updates

Revision ID: 0ef77813315b
Revises: 7d7c2ca49c90
Create Date: 2023-12-13 14:43:49.456622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ef77813315b'
down_revision = '7d7c2ca49c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_form')
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('transfer_to_user',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('transfer_to_user',
               existing_type=mysql.INTEGER(),
               nullable=False)

    op.create_table('new_form',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('centreno', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('centrename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('sessionno', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('caller', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('issuecat', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('descriptionprevious', mysql.TEXT(), nullable=True),
    sa.Column('solution', mysql.TEXT(), nullable=True),
    sa.Column('resolved', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phonenumber', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('transfer_to_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('date_updated', mysql.DATETIME(), nullable=False),
    sa.Column('updated_by', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='new_form_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='new_form_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='new_form_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
