"""updates

Revision ID: ff31ab285326
Revises: 986c1cfe434e
Create Date: 2023-12-12 11:19:11.961230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff31ab285326'
down_revision = '986c1cfe434e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('sessionno',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.alter_column('sessionno',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
